exclude: ^(requirements)/
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--line-length", "100"]
        language_version: python3.11
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "100"]
        language_version: python3.11
        additional_dependencies:
          - pep8-naming
          - flake8-absolute-import
          - flake8-comprehensions
          - flake8-bugbear


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
          - --keep-runtime-typing
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.2
    hooks:
      - id: gitleaks